{% set version = "0.6" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  md5: 07b0ec9fec510352edc617e95ee86469

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyopengl
    - glueviz >=0.9
    - scikit-image
    - matplotlib
    - qt 4.8.*
    - pyqt 4.11.*

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue

extra:
  recipe-maintainers:
    - astrofrog
